- name: Create root directory
  file:
    path: "{{ root }}"
    state: directory
  notify: "{{ notify | default(omit) }}"

- name: Create directories
  file:
    path: "{{ root }}/{{ item.path }}"
    state: directory
  when: item.state == 'directory'
  with_filetree: "{{ directory }}"
  loop_control:
    label: "{{ item.path }}"
  notify: "{{ notify | default(omit) }}"

- name: Copy non-template files
  copy:
    src: "{{ item.src }}"
    dest: "{{ root }}/{{ item.path }}"
    mode: preserve
  when:
    item.state == 'file' and
      (not item.path.endswith('.j2')) and
      (not item.path | basename == '.gitignore')
  with_filetree: "{{ directory }}"
  loop_control:
    label: "{{ item.path }}"
  notify: "{{ notify | default(omit) }}"

- name: Copy template files
  template:
    src: "{{ item.src }}"
    dest: "{{ root }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    mode: preserve
    lstrip_blocks: true
  when:
    item.state == 'file' and
      item.path.endswith('.j2') and
      (not item.path | basename == '.gitignore')
  with_filetree: "{{ directory }}"
  loop_control:
    label: "{{ item.path }}"
  notify: "{{ notify | default(omit) }}"
